version: '3'
services:
  proxy:
    build: ./proxy
    depends_on:
      - web
    ports:
      - "80:80"
  db:
    build: ./db
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432"
  web:
    build: ./web
    volumes:
      - ./web:/app
    command: ./script/server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data:
