version: '3'
services:
  proxy:
    build: ./proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - stats
    ports:
      - "80:80"
  db:
    build: ./db
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432"
  web:
    build: ./web
    volumes:
      - ./web:/app
    command: ./script/server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
  stats:
    build: ./stats
    volumes:
      - ./stats:/app
    ports:
      - "3001:3000"
    command: yarn start
volumes:
  data:
